
spring.application.name=online-voting

spring.datasource.url=jdbc:mysql://localhost:3306/online_voting
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Optional settings
hibernate.show_sql = true
hibernate.format_sql = true
hibernate.hbm2ddl.auto = none
